// Materializes the agent-tokens pi extension on disk and installs the
// process-global bridge it uses to fetch decrypted secrets.
//
// Why a global bridge, not a file read or `import { safeStorage } from
// 'electron'`?
//   - The extension lives under <userDataDir>/pi-agent/extensions/, which is
//     outside the shockwave project. Node's resolver can't find 'electron'
//     from there, and shipping a symlink to node_modules is fragile across
//     dev/prod and asar boundaries.
//   - Writing decrypted secrets to disk for the extension to read defeats the
//     safeStorage encryption we just added.
//   - Pi runs in the same V8 isolate as main, so a function attached to
//     `global` is the cleanest bridge: no disk, no module-resolution dance,
//     and the extension stays plain JS with zero imports.

import path from 'node:path';
import fs from 'node:fs/promises';
import { agentDirFor } from './skillLibrary.js';

const EXTENSION_FILENAME = 'index.js';

// Plain JS — no imports, no TS syntax. Loaded by pi's jiti at session boot.
// The bridge name is namespaced to make conflicts with other globals unlikely.
const EXTENSION_SOURCE = `// Generated by Shockwave. Do not edit — overwritten on each launch.
// Exposes two tools to the pi coding agent:
//   list_agent_secrets — names + descriptions of stored API tokens
//   get_agent_secret    — value of one token by name
// Secrets are fetched via a process-global bridge installed by Shockwave's
// main process at startup. The extension itself touches neither disk nor
// electron APIs.

module.exports = function (pi) {
  async function readSecrets() {
    const bridge = global.__SHOCKWAVE_AGENT_TOKENS;
    if (!bridge || typeof bridge.getSecrets !== 'function') return [];
    try { return (await bridge.getSecrets()) || []; } catch { return []; }
  }

  pi.registerTool({
    name: 'list_agent_secrets',
    label: 'List Agent Secrets',
    description: "Lists API tokens available to you. Returns each token's name and a short description of what it's for. Does not return the token value — call get_agent_secret for that. Use this to check whether a credential you need is already on file before asking the user for one.",
    promptSnippet: 'List available API tokens by name and purpose.',
    parameters: { type: 'object', properties: {}, additionalProperties: false },
    async execute() {
      const secrets = await readSecrets();
      const text = secrets.length === 0
        ? 'No API tokens are currently stored.'
        : secrets.map((s) => '- ' + s.name + (s.description ? ': ' + s.description : '')).join('\\n');
      return {
        content: [{ type: 'text', text: text }],
        details: { count: secrets.length, names: secrets.map((s) => s.name) },
      };
    },
  });

  pi.registerTool({
    name: 'get_agent_secret',
    label: 'Get Agent Secret',
    description: 'Returns the value of one API token by name. Use the exact name from list_agent_secrets. Errors if no token by that name exists.',
    promptSnippet: 'Read one API token by name.',
    promptGuidelines: [
      'Do not echo a token returned by get_agent_secret in your reply, into a file, or into a shell command that prints it. Prefer passing the token via env vars to the subprocess that needs it.',
    ],
    parameters: {
      type: 'object',
      properties: { name: { type: 'string', description: 'Exact name of the secret (from list_agent_secrets).' } },
      required: ['name'],
      additionalProperties: false,
    },
    async execute(_id, params) {
      const secrets = await readSecrets();
      const match = secrets.find((s) => s.name === params.name);
      if (!match) {
        return {
          content: [{ type: 'text', text: 'No secret named "' + params.name + '". Call list_agent_secrets to see available names.' }],
          isError: true,
        };
      }
      return {
        content: [{ type: 'text', text: match.token }],
        details: { name: match.name },
      };
    },
  });
};
`;

export async function ensureAgentTokensExtension(userDataDir) {
  const dir = path.join(agentDirFor(userDataDir), 'extensions', 'agent-tokens');
  await fs.mkdir(dir, { recursive: true });
  const file = path.join(dir, EXTENSION_FILENAME);
  await fs.writeFile(file, EXTENSION_SOURCE, 'utf8');
  return file;
}

export function installAgentTokensBridge(getSecrets) {
  global.__SHOCKWAVE_AGENT_TOKENS = { version: 1, getSecrets };
}
