// Materializes the agent-tokens pi extension on disk and installs the
// process-global bridge it uses to fetch decrypted secrets.
//
// Why a global bridge, not a file read or `import { safeStorage } from
// 'electron'`?
//   - The extension lives under <userDataDir>/pi-agent/extensions/, which is
//     outside the shockwave project. Node's resolver can't find 'electron'
//     from there, and shipping a symlink to node_modules is fragile across
//     dev/prod and asar boundaries.
//   - Writing decrypted secrets to disk for the extension to read defeats the
//     safeStorage encryption we just added.
//   - Pi runs in the same V8 isolate as main, so a function attached to
//     `global` is the cleanest bridge: no disk, no module-resolution dance,
//     and the extension stays plain JS with zero imports.

import path from 'node:path';
import fs from 'node:fs/promises';
import { agentDirFor } from './skillLibrary.js';

const EXTENSION_FILENAME = 'index.js';

// Plain JS — no imports, no TS syntax. Loaded by pi's jiti at session boot.
// The bridge name is namespaced to make conflicts with other globals unlikely.
const EXTENSION_SOURCE = `// Generated by Shockwave. Do not edit — overwritten on each launch.
// Exposes two tools to the pi coding agent:
//   list_agent_secrets — names, descriptions, and (for OAuth) provider/scopes/status
//   get_agent_secret    — a USABLE credential for one secret by name
// Both static API tokens and OAuth connections are surfaced uniformly: the agent
// asks for a credential by name and gets one back. For an OAuth connection,
// get_agent_secret returns a freshly-refreshed access token — refresh happens in
// main, transparently. Everything is fetched via a process-global bridge
// installed by Shockwave's main process at startup; the extension itself touches
// neither disk nor electron APIs.

module.exports = function (pi) {
  function bridge() { return global.__SHOCKWAVE_AGENT_TOKENS; }

  // Metadata only — never token values.
  async function readMeta() {
    const b = bridge();
    if (!b || typeof b.getSecrets !== 'function') return [];
    try {
      const secrets = (await b.getSecrets()) || [];
      return secrets.map((s) => ({
        name: s.name,
        description: s.description || '',
        kind: s.oauth ? 'oauth' : 'static',
        provider: s.oauth ? s.oauth.provider : undefined,
        scopes: s.oauth ? (s.oauth.scopes || []) : undefined,
        status: s.oauth ? s.oauth.status : undefined,
      }));
    } catch { return []; }
  }

  pi.registerTool({
    name: 'list_agent_secrets',
    label: 'List Agent Secrets',
    description: "Lists credentials available to you. For each: its name, a short description, its kind ('static' API token or 'oauth' connection), and for OAuth connections the provider, granted scopes, and connection status. Never returns the value — call get_agent_secret for a usable credential. Use this to check whether a credential you need is already on file before asking the user for one.",
    promptSnippet: 'List available credentials by name, kind, and purpose.',
    parameters: { type: 'object', properties: {}, additionalProperties: false },
    async execute() {
      const items = await readMeta();
      if (items.length === 0) {
        return { content: [{ type: 'text', text: 'No credentials are currently stored.' }], details: { count: 0, names: [] } };
      }
      const text = items.map((s) => {
        let line = '- ' + s.name + ' [' + s.kind + ']';
        if (s.description) line += ': ' + s.description;
        if (s.kind === 'oauth') {
          line += ' (provider: ' + s.provider + ', status: ' + s.status;
          if (s.scopes && s.scopes.length) line += ', scopes: ' + s.scopes.join(' ');
          line += ')';
        }
        return line;
      }).join('\\n');
      return { content: [{ type: 'text', text: text }], details: { count: items.length, names: items.map((s) => s.name) } };
    },
  });

  pi.registerTool({
    name: 'get_agent_secret',
    label: 'Get Agent Secret',
    description: 'Returns a usable credential for one secret by name. For a static secret this is the stored API token; for an OAuth connection this is a fresh access token (refreshed automatically if expired). Use the exact name from list_agent_secrets. Errors if no secret by that name exists, or if an OAuth connection needs to be reconnected by the user.',
    promptSnippet: 'Get a usable credential (API token or fresh OAuth access token) by name.',
    promptGuidelines: [
      'Do not echo a credential returned by get_agent_secret in your reply, into a file, or into a shell command that prints it. Prefer passing it via env vars to the subprocess that needs it.',
      'If get_agent_secret reports an OAuth connection is expired or disconnected, tell the user to reconnect it in Settings — you cannot re-authorize it yourself.',
    ],
    parameters: {
      type: 'object',
      properties: { name: { type: 'string', description: 'Exact name of the secret (from list_agent_secrets).' } },
      required: ['name'],
      additionalProperties: false,
    },
    async execute(_id, params) {
      const b = bridge();
      if (!b || typeof b.getToken !== 'function') {
        return { content: [{ type: 'text', text: 'Credential access is unavailable.' }], isError: true };
      }
      try {
        const value = await b.getToken(params.name);
        return { content: [{ type: 'text', text: value }], details: { name: params.name } };
      } catch (e) {
        return {
          content: [{ type: 'text', text: (e && e.message) ? e.message : ('No secret named "' + params.name + '". Call list_agent_secrets to see available names.') }],
          isError: true,
        };
      }
    },
  });
};
`;

export async function ensureAgentTokensExtension(userDataDir) {
  const dir = path.join(agentDirFor(userDataDir), 'extensions', 'agent-tokens');
  await fs.mkdir(dir, { recursive: true });
  const file = path.join(dir, EXTENSION_FILENAME);
  await fs.writeFile(file, EXTENSION_SOURCE, 'utf8');
  return file;
}

// getSecrets — returns the full decrypted secrets array (used for metadata only
//   by the extension; it never surfaces token values from this).
// getToken(name) — returns a USABLE credential string: the static token, or a
//   freshly-refreshed OAuth access token. Throws with a user-facing message when
//   the name is unknown or an OAuth connection needs reconnecting.
export function installAgentTokensBridge(getSecrets, getToken) {
  global.__SHOCKWAVE_AGENT_TOKENS = { version: 2, getSecrets, getToken };
}
