// Coding-agent integration via @earendil-works/pi-coding-agent.
//
// One live pi AgentSession PER CHAT, kept in a map keyed by sessionId. Sessions
// are PERSISTED (pi writes a JSONL under <agentDir>/sessions) so chats survive
// reload. The DB (src/main/db) is the source of truth for DISPLAY + SEARCH;
// pi's JSONL is the source of truth for CONTINUATION.
//
// Chat IDs are generated by the RENDERER (a UUID minted when the user starts a
// new chat) and handed to pi via SessionManager.create(..., { id }), so every
// event can be stamped with its sessionId from the first millisecond — no
// correlation dance for brand-new chats. Open-vs-new is derived from the DB:
// a row with a jsonlPath means resume; no row means create.
//
// On session create we capture the exact assembled system prompt and store it
// in the DB; on RESUME we hand that stored string back to pi via
// `systemPromptOverride` so the chat continues with the same prompt it was
// created with (pi would otherwise re-derive today's). After each successful
// turn we persist the new messages to the DB; after the first exchange we
// fire-and-forget an auto-title.
//
// Concurrency model:
// - Sends to different chats run concurrently — independent AgentSession objects.
// - A send to a chat that is mid-turn becomes a STEER: pi queues the message
//   and delivers it at the next step boundary of the running turn.
// - A session lives until its chat is deleted (dispose) or the app quits.
//   Idle sessions hold no timers/sockets — just their transcript on the heap.
// - Config change (model/key/thinking) on an idle chat rebuilds its session on
//   the next send, continuing the same JSONL. Mid-turn config changes wait for
//   the turn to finish (steers keep the running session's config).
//
// Skills: before each session create, we compute the effective skill list for
// the active workspace and write it to <agentDir>/settings.json `skills: []`.

import { join } from 'node:path';
import { createAgentSession, AuthStorage, ModelRegistry, SessionManager, DefaultResourceLoader } from '@earendil-works/pi-coding-agent';
import { getSupportedThinkingLevels } from '@earendil-works/pi-ai';
import { getModel, getModels, completeSimple } from '@earendil-works/pi-ai/compat';
import { getCatalogModel } from './modelCatalog.js';
import { agentDirFor, ensureDirs, listBuiltinSkills, listWorkspaceSkills, computeEffectivePaths, writePiSettings } from './skillLibrary.js';
import { ensureAgentTokensExtension } from './agentTokensExtension.js';
import { ensureOpenFileExtension } from './openFileExtension.js';
import { assembleSystemPrompt } from './prompt/index.js';
import { upsertSession, persistMessages, setSessionTitle, getSession } from './db/index.js';

type Emit = (event: any) => void;

type Entry = {
  session: any;
  unsubscribe: (() => void) | null;
  key: string;
  workspacePath: string;
  jsonlPath: string;
  running: boolean;
  // Latest renderer emit callback. The pi subscription is created once per boot
  // but must follow window reloads, so the wrapper reads this ref on every event.
  emit: Emit;
  // Set by the subscription wrapper when a turn ends in a provider error
  // (e.g. image too large); consumed by agentSend's failed-pair splice.
  lastFailureError: string | null;
  // Model handles stashed for the fire-and-forget title call.
  modelObj: any;
  modelRegistry: any;
};

const sessions = new Map<string, Entry>();
// Boot de-dup: a second send to the same chat while its session is still
// booting must await the same boot, not create a duplicate (two managers on
// one JSONL would corrupt it).
const booting = new Map<string, Promise<Entry>>();

// Prompt for the fire-and-forget title generation (hermes' wording).
const TITLE_PROMPT = 'Generate a short, descriptive title (3-7 words) for a conversation that starts with the following exchange. The title should capture the main topic or intent. Return ONLY the title text, nothing else. No quotes, no punctuation at the end, no prefixes.';

function makeKey({ workspacePath, provider, model, apiKey, baseUrl, contextWindow, thinkingLevel }) {
  // Config-only key. A config change on an idle chat reboots its session but
  // CONTINUES the same chat (re-opening its JSONL) rather than starting a new
  // conversation.
  return [workspacePath, provider, model, apiKey, baseUrl ?? '', contextWindow ?? '', thinkingLevel ?? ''].join(' ');
}

// Flatten a pi message's content to plain text (for the title exchange).
function textOf(content: any): string {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    return content.filter((c) => c && c.type === 'text' && typeof c.text === 'string').map((c) => c.text).join('');
  }
  return '';
}

// Resolve a (provider, model) to a runnable pi Model. Pi's bundled catalog wins
// when it has the model — it carries the vetted thinkingLevelMap + provider
// dispatch. When pi doesn't know the model (newer than its bundled list), we
// SYNTHESIZE one from the models.dev catalog: the provider's API wiring
// (api/baseUrl/compat) is a per-provider constant, so we clone it from any model
// pi already knows for that provider, then overlay the models.dev metadata.
// thinkingLevelMap is deliberately omitted — it's provider-specific and can't be
// inferred safely — so synthesized reasoning models expose the standard
// off..high set; their top tier (e.g. xhigh) returns once pi's catalog updates.
// Returns null only when neither pi nor models.dev knows the model, or pi has no
// template for the provider at all (can't reach it).
async function resolveModel(provider, model) {
  if (!provider || !model) return null;
  const real = getModel(provider, model);
  if (real) return real;

  const rec = await getCatalogModel(provider, model);
  if (!rec) return null;
  const sibling = getModels(provider)[0]; // per-provider dispatch template
  if (!sibling) return null;
  return {
    id: rec.id,
    name: rec.name,
    api: sibling.api,
    provider,
    baseUrl: sibling.baseUrl,
    compat: sibling.compat,
    reasoning: rec.reasoning,
    input: rec.input,
    cost: rec.cost,
    contextWindow: rec.contextWindow,
    maxTokens: rec.maxTokens,
  };
}

// Reasoning levels for the dropdown: 'off' plus the model's models.dev
// reasoning_options, translated to pi's names (so the level shown is exactly the
// one that runs) and de-duplicated (models.dev lists both 'xhigh' and 'max',
// which are the same tier in pi's language). Non-reasoning models get just
// ['off'] — the UI hides the control when the list has one entry.
export async function listThinkingLevels(provider, model) {
  if (!provider) return ['off'];
  if (provider === 'openai-compatible') return ['off', 'minimal', 'low', 'medium', 'high'];
  if (!model) return ['off'];
  try {
    const rec = await getCatalogModel(provider, model);
    if (!rec || !rec.reasoning) return ['off'];
    return [...new Set(['off', ...rec.reasoningLevels.map(toPiThinkingLevel)])];
  } catch {
    return ['off'];
  }
}

async function disposeEntry(sessionId: string) {
  const entry = sessions.get(sessionId);
  if (!entry) return;
  sessions.delete(sessionId);
  if (entry.unsubscribe) {
    try { entry.unsubscribe(); } catch { /* already unsubscribed */ }
    entry.unsubscribe = null;
  }
  try { await entry.session.abort(); } catch { /* best-effort */ }
  try { entry.session.dispose(); } catch { /* best-effort */ }
}

// models.dev's top reasoning level is named 'max'; pi's is 'xhigh' — same thing,
// different name. Translate before handing the level to pi, or pi wouldn't
// recognize 'max' and would clamp it down to 'off' (no reasoning at all).
function toPiThinkingLevel(level: string): string {
  return level === 'max' ? 'xhigh' : level;
}

async function bootSession(sessionId: string, opts, emitEvent: Emit): Promise<Entry> {
  const { workspacePath, provider, model, apiKey, baseUrl, contextWindow, thinkingLevel, userDataDir, builtinDir, wsBuiltinSkills, unattended, source, cronTitle } = opts;
  const level = toPiThinkingLevel(thinkingLevel || 'off');

  // Recompute the effective skill list + materialize extensions before boot.
  await ensureDirs(userDataDir);
  const builtins = await listBuiltinSkills(builtinDir);
  const wsSkills = await listWorkspaceSkills(workspacePath);
  const effectivePaths = computeEffectivePaths(builtins, wsBuiltinSkills, wsSkills);
  const agentTokensPath = await ensureAgentTokensExtension(userDataDir);
  const openFilePath = await ensureOpenFileExtension(userDataDir);
  await writePiSettings(userDataDir, { skills: effectivePaths, extensions: [agentTokensPath, openFilePath] });

  // Config change on an idle chat: replace its session (same JSONL, new config).
  await disposeEntry(sessionId);

  const authStorage = AuthStorage.inMemory();
  const modelRegistry = ModelRegistry.create(authStorage);

  let modelObj;
  if (provider === 'openai-compatible') {
    modelRegistry.registerProvider('openai-compatible', {
      baseUrl,
      apiKey: apiKey || 'local',
      api: 'openai-completions',
      models: [{
        id: model,
        name: model,
        reasoning: level !== 'off',
        input: ['text'],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: contextWindow || 128000,
        maxTokens: 16384,
      }],
    });
    modelObj = modelRegistry.find('openai-compatible', model);
  } else {
    authStorage.setRuntimeApiKey(provider, apiKey);
    // Pi's bundled model if it has it, else a descriptor synthesized from the
    // models.dev catalog (so models newer than pi's list still run).
    modelObj = await resolveModel(provider, model);
    if (!modelObj) throw new Error(`Model "${model}" not found for provider "${provider}".`);
  }

  // Open-vs-new comes from the DB: a stored row means this chat has a JSONL to
  // resume; otherwise pi creates a fresh one UNDER OUR ID so the renderer's
  // pre-generated sessionId is the session's real identity.
  const agentDir = agentDirFor(userDataDir);
  const row = getSession(sessionId);
  let sessionManager;
  let promptOverride: string;
  if (row?.jsonlPath) {
    sessionManager = SessionManager.open(row.jsonlPath);
    promptOverride = row.systemPrompt ?? await assembleSystemPrompt(workspacePath);
  } else {
    sessionManager = SessionManager.create(workspacePath, join(agentDir, 'sessions'), { id: sessionId });
    // `unattended` (a cron run) adds the unattended-override to the prompt. It's
    // frozen on the row here, so a fresh uuid per cron run always carries it.
    promptOverride = await assembleSystemPrompt(workspacePath, { unattended: !!unattended });
  }

  const resourceLoader = new DefaultResourceLoader({
    cwd: workspacePath,
    agentDir,
    // Re-use the (possibly stored) assembled prompt verbatim. pi appends
    // AGENTS.md + skills + date on top, as always.
    systemPromptOverride: () => promptOverride,
  });
  await resourceLoader.reload();

  const { session } = await createAgentSession({
    cwd: workspacePath,
    agentDir,
    model: modelObj,
    thinkingLevel: level as any,
    authStorage,
    modelRegistry,
    sessionManager,
    resourceLoader,
  });

  const entry: Entry = {
    session,
    unsubscribe: null,
    // Key with the RAW setting (matches the reuse-check at boot), not the
    // pi-translated level — else a 'max' setting would rebuild every send.
    key: makeKey({ workspacePath, provider, model, apiKey, baseUrl, contextWindow, thinkingLevel: thinkingLevel || 'off' }),
    workspacePath,
    jsonlPath: session.sessionFile,
    running: false,
    emit: emitEvent,
    lastFailureError: null,
    modelObj,
    modelRegistry,
  };

  // Every event out of this session is stamped with its sessionId so the
  // renderer can route it to the right chat regardless of which is visible.
  entry.unsubscribe = session.subscribe((event) => {
    if (event?.type === 'agent_end' && Array.isArray(event.messages)) {
      const failure = event.messages.find(
        (m) => m?.role === 'assistant' && m?.stopReason === 'error' && m?.errorMessage,
      );
      if (failure) entry.lastFailureError = failure.errorMessage;
    }
    entry.emit({ ...event, sessionId });
  });

  sessions.set(sessionId, entry);

  // Record the chat in the DB. For a brand-new chat this stores the exact
  // assembled prompt we just used (frozen); for a resume/continue the insert
  // conflicts and only refreshes the path + recency, preserving the frozen
  // prompt + title.
  upsertSession({
    sessionId,
    workspace: workspacePath,
    jsonlPath: entry.jsonlPath,
    systemPrompt: promptOverride,
    model: model ?? null,
    source: source ?? 'desktop',
    // Identity within the source. Cron's is the job name (already threaded here
    // as cronTitle); an interactive desktop chat has no external id.
    sourceId: cronTitle ?? null,
    now: Date.now(),
  });

  // Cron runs pre-title their chat with the job name (skipping auto-title —
  // maybeGenerateTitle no-ops once a title exists). Only on a fresh row.
  if (cronTitle) {
    const existing = getSession(sessionId);
    if (existing && !existing.title) setSessionTitle(sessionId, cronTitle);
  }

  // Tell the renderer this chat's session is live (title + star from the DB).
  const dbRow = getSession(sessionId);
  entry.emit({ type: 'shockwave_session', sessionId, title: dbRow?.title ?? null, starred: !!dbRow?.starred });

  return entry;
}

async function ensureSession(sessionId: string, opts, emitEvent: Emit): Promise<Entry> {
  const key = makeKey({ ...opts, thinkingLevel: opts.thinkingLevel || 'off' });
  const existing = sessions.get(sessionId);
  if (existing) {
    existing.emit = emitEvent;
    // Reuse when config is unchanged — or unconditionally while running (a
    // mid-turn config change applies on the next idle send, never mid-turn).
    if (existing.running || (existing.key === key && existing.workspacePath === opts.workspacePath)) {
      return existing;
    }
  }
  const inflight = booting.get(sessionId);
  if (inflight) {
    const entry = await inflight;
    entry.emit = emitEvent;
    return entry;
  }
  const boot = bootSession(sessionId, opts, emitEvent).finally(() => booting.delete(sessionId));
  booting.set(sessionId, boot);
  return boot;
}

// Fire-and-forget: after the first exchange, ask pi's own LLM for a short title.
// A single completeSimple call — NOT the agent loop — so it never touches the
// transcript or runs tools.
function maybeGenerateTitle(entry: Entry, sessionId: string, messages: any[]) {
  const row = getSession(sessionId);
  if (!row || row.title) return;
  const firstUser = messages.find((m) => m?.role === 'user');
  const firstAsst = messages.find((m) => m?.role === 'assistant');
  if (!firstUser) return;
  const { modelObj, modelRegistry } = entry;
  if (!modelObj || !modelRegistry) return;

  const exchange = `User: ${textOf(firstUser.content)}\n\nAssistant: ${textOf(firstAsst?.content)}`.slice(0, 2000);
  (async () => {
    try {
      const auth = await modelRegistry.getApiKeyAndHeaders(modelObj);
      if (!auth?.ok) return;
      const res = await completeSimple(
        modelObj,
        { messages: [{ role: 'user', content: `${TITLE_PROMPT}\n\n${exchange}`, timestamp: Date.now() }] },
        { apiKey: auth.apiKey, headers: auth.headers, env: auth.env, maxTokens: 32 },
      );
      const title = (res?.content ?? [])
        .filter((c) => c?.type === 'text')
        .map((c) => c.text)
        .join('')
        .trim()
        .replace(/^["']|["']$/g, '')
        .slice(0, 100);
      if (title) {
        setSessionTitle(sessionId, title);
        entry.emit({ type: 'shockwave_session_titled', sessionId, title });
      }
    } catch { /* title is best-effort */ }
  })();
}

export async function agentSend(opts, emitEvent: Emit) {
  const { sessionId, text, images, workspacePath, provider, model, apiKey } = opts;
  if (!sessionId) throw new Error('agentSend requires a sessionId.');
  if (!workspacePath) throw new Error('Open a workspace first.');
  if (!provider) throw new Error('Coding agent provider not configured.');
  if (!model) throw new Error('Coding agent model not configured.');
  if (provider !== 'openai-compatible' && !apiKey) throw new Error('Coding agent API key not configured. Open Settings → LLM / Agent.');

  const hasImages = Array.isArray(images) && images.length > 0;

  // Mid-turn send → steer: pi queues the message and delivers it at the next
  // step boundary of the running turn. Events keep flowing through the
  // existing subscription; persistence happens when the original turn ends.
  const live = sessions.get(sessionId);
  if (live?.running) {
    live.emit = emitEvent;
    await live.session.prompt(text, { ...(hasImages ? { images } : {}), streamingBehavior: 'steer' });
    return;
  }

  const entry = await ensureSession(sessionId, opts, emitEvent);
  entry.lastFailureError = null;
  entry.running = true;
  try {
    await entry.session.prompt(text, hasImages ? { images } : undefined);
  } finally {
    entry.running = false;
  }

  if (entry.lastFailureError) {
    // Pi pushes the user message before the API call and a failure assistant
    // message after, so a provider error (e.g. image too large) leaves both
    // stuck in context to re-poison every subsequent turn. Splice the pair out
    // and tell the renderer to drop the matching transcript entry.
    const errorMessage = entry.lastFailureError;
    entry.lastFailureError = null;
    const msgs = entry.session.state?.messages;
    if (Array.isArray(msgs) && msgs.length >= 2) {
      const last = msgs[msgs.length - 1];
      const prev = msgs[msgs.length - 2];
      if (last?.role === 'assistant' && last?.stopReason === 'error' && prev?.role === 'user') {
        msgs.splice(msgs.length - 2, 2);
      }
    }
    entry.emit({ type: 'agent_send_failed', errorMessage, sessionId });
    return;
  }

  // Turn succeeded: persist the new complete messages, then maybe title.
  const msgs = entry.session.state?.messages ?? [];
  try { persistMessages(sessionId, msgs, Date.now()); } catch { /* persistence is best-effort */ }
  maybeGenerateTitle(entry, sessionId, msgs);
}

export async function agentAbort(sessionId: string) {
  const entry = sessions.get(sessionId);
  if (entry) {
    try { await entry.session.abort(); } catch { /* best-effort */ }
  }
}

// Chat deleted — abort any in-flight turn and drop the live session. The JSONL
// and DB rows are the caller's business.
export async function agentDisposeSession(sessionId: string) {
  await disposeEntry(sessionId);
}

// App quit — tear down every live session.
export async function agentDisposeAll() {
  await Promise.all([...sessions.keys()].map((id) => disposeEntry(id)));
}

// Which chats have a turn in flight right now (renderer hydrates its running
// set from this on mount/reload).
export function agentRunningSessions(): string[] {
  return [...sessions.entries()].filter(([, e]) => e.running).map(([id]) => id);
}
