// Materializes the link-index pi extension on disk and installs the bridge
// it uses to query the workspace.
//
// Single tool exposed to the agent:
//   resolve_link — basename → workspace-relative path + backlinks
//
// Creating a file or inserting a wiki-link `[[...]]` doesn't justify its own
// tool — the agent uses pi's built-in `write` / `edit` for that.
//
// Same pattern as agentTokensExtension.js: extension file is plain JS with
// no imports, installed under <userDataDir>/pi-agent/extensions/, calls back
// into main via a process-global bridge that we install at startup.

import path from 'node:path';
import fs from 'node:fs/promises';
import { agentDirFor } from './skillLibrary.js';

const EXTENSION_FILENAME = 'index.js';

// Plain JS — pi's jiti loads this at session boot. No TS, no imports, no
// electron APIs (the bridge does the work).
const EXTENSION_SOURCE = `// Generated by Shockwave. Do not edit — overwritten on each launch.
// Exposes one tool that queries the user's workspace link graph:
//   resolve_link — basename lookup + backlinks

module.exports = function (pi) {
  function bridge() {
    return global.__SHOCKWAVE_LINK_INDEX;
  }

  pi.registerTool({
    name: 'resolve_link',
    label: 'Resolve Wiki-link',
    description:
      "Resolves a wiki-link basename to its workspace-relative file path and lists every file that links to it.\\n\\n" +
      "Input is a basename only — no folder paths, no \`.md\` extension. Matching is case-insensitive " +
      "(\`Foo\`, \`foo\`, \`FOO\` all hit the same file). One call replaces a find-by-name plus a grep-for-backlinks.\\n\\n" +
      "Returns { path, backlinks }. If no file matches, path is null and backlinks is empty — not an error.",
    promptSnippet:
      'Look up a wiki-link target by basename and get its backlinks in one call.',
    promptGuidelines: [
      'Use resolve_link instead of grep/find when locating a file by basename or enumerating its backlinks.',
      'Pass only the basename to resolve_link — never a folder path or a \`.md\` extension.',
    ],
    parameters: {
      type: 'object',
      properties: {
        basename: {
          type: 'string',
          description: 'The wiki-link basename, e.g. "Foo" for [[Foo]]. No path, no ".md".',
        },
      },
      required: ['basename'],
      additionalProperties: false,
    },
    async execute(_id, params) {
      const b = bridge();
      if (!b) {
        return {
          content: [{ type: 'text', text: 'Link index bridge not available.' }],
          isError: true,
        };
      }
      const { path: filePath, backlinks } = await b.resolve(params.basename);
      if (!filePath) {
        return {
          content: [{ type: 'text', text: 'No file with basename "' + params.basename + '".' }],
          details: { path: null, backlinks: [] },
        };
      }
      const lines = ['Path: ' + filePath];
      if (backlinks.length === 0) {
        lines.push('Backlinks: none');
      } else {
        lines.push('Backlinks (' + backlinks.length + '):');
        for (const p of backlinks) lines.push('  - ' + p);
      }
      return {
        content: [{ type: 'text', text: lines.join('\\n') }],
        details: { path: filePath, backlinks: backlinks },
      };
    },
  });
};
`;

export async function ensureLinkIndexExtension(userDataDir) {
  const dir = path.join(agentDirFor(userDataDir), 'extensions', 'link-index');
  await fs.mkdir(dir, { recursive: true });
  const file = path.join(dir, EXTENSION_FILENAME);
  await fs.writeFile(file, EXTENSION_SOURCE, 'utf8');
  return file;
}

export function installLinkIndexBridge(impl) {
  global.__SHOCKWAVE_LINK_INDEX = { version: 1, ...impl };
}
