// Materializes the open-file pi extension on disk and installs the process-
// global bridge it uses to ask the renderer to open a file in the UI.
//
// Same rationale as agentTokensExtension.ts for the global-bridge shape: the
// extension lives under <userDataDir>/pi-agent/extensions/ (outside this
// project, so it can't import 'electron'), and pi runs in the same V8 isolate
// as main, so a function on `global` is the cleanest bridge. The bridge in main
// validates the path against the active workspace and pushes `agent:openFile`
// to the renderer.

import path from 'node:path';
import fs from 'node:fs/promises';
import { agentDirFor } from './skillLibrary.js';

const EXTENSION_FILENAME = 'index.js';

// Plain JS — no imports, no TS syntax. Loaded by pi's jiti at session boot.
const EXTENSION_SOURCE = `// Generated by Shockwave. Do not edit — overwritten on each launch.
// Exposes one tool to the pi coding agent:
//   open_file — opens a file in the Shockwave UI (new tab) so the user sees it.
// Routed through a process-global bridge installed by Shockwave's main process.

module.exports = function (pi) {
  pi.registerTool({
    name: 'open_file',
    label: 'Open File',
    description: "Opens a file in the Shockwave app UI in a new tab so the user can see it. Call this when the user asks you to open, show, or display a file. The path is relative to your working directory (the workspace root). Only files inside the workspace that the app can display (.md, images, video, .excalidraw) can be opened; opening does not modify the file.",
    promptSnippet: 'Open a file in the app UI (new tab) when the user asks to see it.',
    parameters: {
      type: 'object',
      properties: {
        path: { type: 'string', description: 'Workspace-relative path to the file to open, e.g. "Diagrams/Flow.excalidraw".' },
      },
      required: ['path'],
      additionalProperties: false,
    },
    async execute(_id, params) {
      const bridge = global.__SHOCKWAVE_OPEN_FILE;
      if (typeof bridge !== 'function') {
        return { content: [{ type: 'text', text: 'Open-file bridge is unavailable.' }], isError: true };
      }
      try {
        const res = await bridge(params.path);
        if (res && res.ok) {
          return { content: [{ type: 'text', text: 'Opened ' + params.path + ' in the app.' }], details: { path: params.path } };
        }
        return { content: [{ type: 'text', text: (res && res.error) || 'Could not open the file.' }], isError: true };
      } catch (e) {
        return { content: [{ type: 'text', text: 'Could not open the file: ' + (e && e.message || e) }], isError: true };
      }
    },
  });
};
`;

export async function ensureOpenFileExtension(userDataDir) {
  const dir = path.join(agentDirFor(userDataDir), 'extensions', 'open-file');
  await fs.mkdir(dir, { recursive: true });
  const file = path.join(dir, EXTENSION_FILENAME);
  await fs.writeFile(file, EXTENSION_SOURCE, 'utf8');
  return file;
}

// handler(relPath) → Promise<{ ok: true } | { ok: false, error: string }>.
export function installOpenFileBridge(handler) {
  global.__SHOCKWAVE_OPEN_FILE = handler;
}
